device: cpu
output_dir: output/quarot
quantization:
    pipeline: [outlier_reduction, ptq]
    outlier_reduction:
        algorithm: QuaRot
        online: false
    ptq:
        algorithm: Gptq
        datasetname: wikitext
        groupsize: 64
        numsamples: 64
        sym: true
        wbits: 4
    
