device: cuda
evaluation:
    tasks:
        MMBench_dev_en:
            class: ImageMCQDataset
            dataset: MMBench_dev_en
output_dir: output/spinquant
quantization:
    outlier_reduction:
        algorithm: SpinQuant
        max_steps: 100
        online: false
        per_device_train_batch_size: 2
        w_groupsize: 64
        a_bits: 8
        k_bits: 8
        v_bits: 8
        a_asym: False
        a_groupsize: 64
    pipeline:
        - outlier_reduction
